services:

  postgres:
    image: postgres:17

    environment:
      POSTGRES_DB: ${ENV_CLIMBAPP_POSTGRES_DB}
      POSTGRES_USER: ${ENV_CLIMBAPP_POSTGRES_USER}
      #The application should not receive the database password as an environment variable.
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password

    secrets:
      # Docker secret is mounted with different filenames depending on the consumer:
      # PostgreSQL: /run/secrets/postgres_password
      - source: postgres_password
        target: postgres_password

    volumes:
      - postgres-data:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${ENV_CLIMBAPP_POSTGRES_USER} -d ${ENV_CLIMBAPP_POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    # Make container port 5432 accessible through host port 5432.
    # This port mapping is only necessary for clients running OUTSIDE
    # the Docker Compose network, such as Spring Boot running locally
    # on Windows or a database client such as pgAdmin.
    #
    # Containers inside the same Compose network can connect directly
    # using the service name and container port:
    #
    #   postgres:5432
    #
    # They do NOT need to use:
    #
    #   localhost:5432
    ports:
      - "5432:5432"
      #   ↑      ↑
      # host   container
      #      Windows
      #   localhost:5432
      #       │
      #       │ port mapping
      #       ▼
      #   Docker container
      #   PostgreSQL:5432



  mongo:
    image: mongo:7

    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb

    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      timeout: 5s
      retries: 5

    # Make the container port 27017 accessible through the host port 27017.
    # Containers inside the same Compose network connect using:
    #
    #   mongo:27017
    #
    # localhost inside a container refers to that same container,
    # not to MongoDB.
    ports:
      - "27017:27017"


  enrollment-service:
    build:
      context: ./services/enrollment-service

    image: enrollment-service:local

    # So we can try kubernetes reach by
    #  kubectl port-forward service/enrollment-service 9091:9091
    #  Docker --> Invoke-RestMethod http://localhost:8081/enrollments
    #  Kubernetes --> Invoke-RestMethod http://localhost:9091/enrollments
    ports:
      - "${ENV_ENROLLMENT_PORT}:8081"

    environment:
      SPRING_PROFILES_ACTIVE: docker
      ENROLLMENT_MONGO_DB: ${ENV_ENROLLMENT_MONGO_DB}
      COURSE_SERVICE_BASE_URL: ${ENV_CLIMBAPP_SERVICE_BASE_URL}

    depends_on:
      - app
      - mongo


  app:
    # it will build climbing-management-sb-app:latest when "docker compose up -d"
    # when we build it manually, we set the tag "docker build -t climbing-management-sb:2.0 ."
    build: .


    # Make the Spring Boot container's port 8080 accessible
    # through the host port defined by ENV_APP_PORT.
    #
    # Format:
    #   HOST_PORT:CONTAINER_PORT
    #
    # If ENV_APP_PORT=8080:
    #
    #   Windows localhost:8080
    #          │
    #          ▼
    #   Docker app container:8080
    #
    # The application itself listens on port 8080 inside the container.

    # So we can try kubernetes reach by
    #  kubectl port-forward service/climbing-management-service 9090:9090
    #  Docker --> Invoke-RestMethod http://localhost:8080/jpa/courses
    #  Kubernetes --> Invoke-RestMethod http://localhost:9090/jpa/courses
    ports:
      - "${ENV_CLIMBAPP_PORT}:8080"

    # Docker mounts the container's root filesystem as read-only
    read_only: true

    # Explicitly give /tmp writable space:
    tmpfs:
      - /tmp

    environment:
      SPRING_PROFILES_ACTIVE: docker

      # container    .env / Compose
      # variable
      #   ↓           ↓
      CLIMBAPP_MONGO_DB: ${ENV_CLIMBAPP_MONGO_DB}
      CLIMBAPP_POSTGRES_USER: ${ENV_CLIMBAPP_POSTGRES_USER}
      CLIMBAPP_POSTGRES_DB: ${ENV_CLIMBAPP_POSTGRES_DB}

    secrets:
      # Docker secret is mounted with different filenames depending on the consumer:
      # App: /run/secrets/spring.datasource.password
      - source: postgres_password
        target: spring.datasource.password

    healthcheck:
      # Invoke-RestMethod http://localhost:8080/actuator/health/liveness
      # Invoke-RestMethod http://localhost:8080/actuator/health/readiness
      test: [ "CMD-SHELL", "wget -q --spider http://localhost:8080/actuator/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

    depends_on:
      postgres:
        condition: service_healthy
      mongo:
        #  condition: service_started
        condition: service_healthy


  kafka:
    image: apache/kafka:4.3.1
    container_name: kafka

    ports:
      - "8082:8082"

    # Windows / IntelliJ
    #       ↓
    # localhost:8082
    #       ↓
    # Kafka container :8082

    # Other Docker containers
    #         ↓
    #   kafka:18082
    #         ↓
    # Kafka internal listener

    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: CONTROLLER://:29093,PLAINTEXT_HOST://:8082,PLAINTEXT://:18082
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_HOST://localhost:8082,PLAINTEXT://kafka:18082
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_SHARE_COORDINATOR_STATE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_SHARE_COORDINATOR_STATE_TOPIC_MIN_ISR: 1

      # Explicit Kafka cluster ID and log directory, because Apache’s KRaft examples define them explicitly
      CLUSTER_ID: 4L6g3nShT-eMCtK--X86sw
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:18082 --list > /dev/null 2>&1"
        ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s


  # One-shot initialization service.
  #
  # It waits until Kafka is healthy, creates the required topic,
  # and then exits successfully.(for testing purposes).
  kafka-init:
    image: apache/kafka:4.3.1

    depends_on:
      - kafka

    entrypoint: [ "/bin/sh", "-c" ]

    # --if-not-exists --> so starting Compose again does not fail because the topic already exists.
    # docker exec kafka /opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:18082 --list
    # docker exec kafka /opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:18082 --describe --topic course-events
    command: >
      "
      /opt/kafka/bin/kafka-topics.sh
      --bootstrap-server kafka:18082
      --create
      --if-not-exists
      --topic course-events
      --partitions 2
      --replication-factor 1
      &&
      /opt/kafka/bin/kafka-topics.sh
      --bootstrap-server kafka:18082
      --create
      --if-not-exists
      --topic course-events-dlt
      --partitions 2
      --replication-factor 1
      "
    restart: "no"


volumes:
  postgres-data:
  mongo-data:
  mongo-config:

# A service can reference a secret only if that secret is declared at the top-level Compose scope.
secrets:
  postgres_password:
    file: ./secrets/spring.datasource.password