services:

  postgres:
    image: postgres:17

    environment:
      POSTGRES_DB: ${ENV_CLIMBAPP_POSTGRES_DB}
      POSTGRES_USER: ${ENV_CLIMBAPP_POSTGRES_USER}
      #The application should not receive the database password as an environment variable.
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password

    secrets:
      # Docker secret is mounted with different filenames depending on the consumer:
      # PostgreSQL: /run/secrets/postgres_password
      - source: postgres_password
        target: postgres_password

    volumes:
      - postgres-data:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${ENV_CLIMBAPP_POSTGRES_USER} -d ${ENV_CLIMBAPP_POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    # Make container port 5432 accessible through host port 5432.
    # This port mapping is only necessary for clients running OUTSIDE
    # the Docker Compose network, such as Spring Boot running locally
    # on Windows or a database client such as pgAdmin.
    #
    # Containers inside the same Compose network can connect directly
    # using the service name and container port:
    #
    #   postgres:5432
    #
    # They do NOT need to use:
    #
    #   localhost:5432
    ports:
      - "5432:5432"
      #   ↑      ↑
      # host   container
      #      Windows
      #   localhost:5432
      #       │
      #       │ port mapping
      #       ▼
      #   Docker container
      #   PostgreSQL:5432



  mongo:
    image: mongo:7

    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb

    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      timeout: 5s
      retries: 5

    # Make the container port 27017 accessible through the host port 27017.
    # Containers inside the same Compose network connect using:
    #
    #   mongo:27017
    #
    # localhost inside a container refers to that same container,
    # not to MongoDB.
    ports:
      - "27017:27017"


  enrollment-service:
    build:
      context: ./services/enrollment-service

    image: enrollment-service:local

    ports:
      - "${ENV_ENROLLMENT_PORT}:8081"

    environment:
      SPRING_PROFILES_ACTIVE: docker
      ENROLLMENT_MONGO_DB: ${ENV_ENROLLMENT_MONGO_DB}
      COURSE_SERVICE_BASE_URL: ${ENV_CLIMBAPP_SERVICE_BASE_URL}

    depends_on:
      - app
      - mongo


  app:
    # it will build climbing-management-sb-app:latest when "docker compose up -d"
    # when we build it manually, we set the tag "docker build -t climbing-management-sb:2.0 ."
    build: .


    # Make the Spring Boot container's port 8080 accessible
    # through the host port defined by ENV_APP_PORT.
    #
    # Format:
    #   HOST_PORT:CONTAINER_PORT
    #
    # If ENV_APP_PORT=8080:
    #
    #   Windows localhost:8080
    #          │
    #          ▼
    #   Docker app container:8080
    #
    # The application itself listens on port 8080 inside the container.
    ports:
      - "${ENV_CLIMBAPP_PORT}:8080"

    # Docker mounts the container's root filesystem as read-only
    read_only: true

    # Explicitly give /tmp writable space:
    tmpfs:
      - /tmp

    environment:
      SPRING_PROFILES_ACTIVE: docker

      # container    .env / Compose
      # variable
      #   ↓           ↓
      CLIMBAPP_MONGO_DB: ${ENV_CLIMBAPP_MONGO_DB}
      CLIMBAPP_POSTGRES_USER: ${ENV_CLIMBAPP_POSTGRES_USER}
      CLIMBAPP_POSTGRES_DB: ${ENV_CLIMBAPP_POSTGRES_DB}

    secrets:
      # Docker secret is mounted with different filenames depending on the consumer:
      # App: /run/secrets/spring.datasource.password
      - source: postgres_password
        target: spring.datasource.password

    healthcheck:
      # Invoke-RestMethod http://localhost:8080/actuator/health/liveness
      # Invoke-RestMethod http://localhost:8080/actuator/health/readiness
      test: [ "CMD-SHELL", "wget -q --spider http://localhost:8080/actuator/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

    depends_on:
      postgres:
        condition: service_healthy
      mongo:
     #  condition: service_started
        condition: service_healthy

volumes:
  postgres-data:
  mongo-data:
  mongo-config:

# A service can reference a secret only if that secret is declared at the top-level Compose scope.
secrets:
  postgres_password:
    file: ./secrets/spring.datasource.password