
# I# IntelliJ: Run ? Edit Configurations ? Spring Boot configuration
## Active profiles: local Active profiles : set to local
### spring.profiles.active=local

#### POSTGRES
spring.datasource.url=jdbc:postgresql://localhost:5432/climbing_management
spring.datasource.username=postgres
spring.datasource.password=root

#### MONGO
spring.mongodb.uri=mongodb://localhost:27017/climbing_management
spring.mongodb.database=climbing_management


#### KAFKA
# Kafka broker used when the Spring Boot application runs directly from Windows / IntelliJ.
spring.kafka.bootstrap-servers=localhost:8082

