apiVersion: v1
kind: Service

metadata:
  name: enrollment-service

spec:
  selector:
    # The Service sends traffic to Pods with this label.
    app: enrollment-service
    deployment: manual

  ports:
    - protocol: TCP
      # Port exposed by the Service.
      port: 9091

      # Port exposed by the application container.
      targetPort: 8081

  # ClusterIP makes the application available inside the cluster.
  type: ClusterIP

  # Kubernetes Service provides a stable internal endpoint.
  #
  # Service
  # enrollment-service:8081
  #             │
  #       ┌─────┴─────┐
  #       ▼           ▼
  # Enrollment Pod   Enrollment Pod
  #      :8081        :8081
  #
  # The Service dynamically routes traffic to Ready Pods matching the selector:
  #     - app=enrollment-service
  #     - deployment=manual