apiVersion: v1
kind: ConfigMap

metadata:
  name: enrollment-service-config

data:
  APP_NAME: enrollment-service
  LOG_LEVEL: INFO

  # Database configuration.
  # These values are not secrets, so they belong in a ConfigMap.
  ENROLLMENT_MONGO_DB: enrollment_management
  COURSE_SERVICE_BASE_URL: http://climbing-management-service:9090


  # A ConfigMap stores non-sensitive configuration separately
  # from the container image.
  #
  # It can be injected into Pods as environment variables
  # or mounted as files.

  #  ConfigMap → non-sensitive configuration
  #  Secret    → sensitive configuration