


# MongoDB runs inside Docker and is configured as a replica set.
#
# Inside the Docker network, the replica-set member may identify itself as:
#
#   mongo:27017
#
# This hostname works between Docker containers:
#
#   app container
#        ?
#        ?
#   mongo:27017
#
# However, applications running directly on Windows, such as MongoDB Compass,
# may not be able to resolve the Docker hostname "mongo".
#
# Compass can initially connect through localhost:27017, but replica-set
# discovery may then redirect it to mongo:27017.
#
# Using directConnection=true tells Compass to use the exact MongoDB instance
# specified in the connection string instead of trying to discover another
# replica-set member.
#
# MongoDB Compass connection:
#
# mongodb://localhost:27017/enrollment_management?replicaSet=rs0&directConnection=true

#### MONGO
spring.mongodb.uri=mongodb://localhost:27017/enrollment_management
spring.mongodb.database=enrollment_management

# Course Service URL to enrollment-service
course-service.base-url=http://localhost:8080

