# Enrollment container
# ?
# ??? localhost:8080  ? Course Service
# ?
# ??? localhost:27017 ? MongoDB


# MongoDB connection used when Enrollment Service runs inside Docker.
spring.mongodb.uri=mongodb://mongo:27017/${ENROLLMENT_MONGO_DB}

# Course Service address used when Enrollment Service runs inside Docker.
course-service.base-url=${CLIMBAPP_SERVICE_BASE_URL}