spring.application.name=enrollment-service

server.port=8081



#### MONGODB UUID
spring.mongodb.representation.uuid=standard

#### KAFKA CONSUMER
spring.kafka.consumer.group-id=enrollment-service

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer


# Wrap the real JSON deserializer so deserialization failures
# can be handled by Spring Kafka's container error handling.
# PREVIOUS: spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JacksonJsonDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
##       ?
# Real delegate used by ErrorHandlingDeserializer.
spring.kafka.consumer.properties[spring.deserializer.value.delegate.class]=org.springframework.kafka.support.serializer.JacksonJsonDeserializer


# Deserialize Kafka JSON into Enrollment's own local event class.
spring.kafka.consumer.properties[spring.json.value.default.type]=com.rubenmarin.enrollmentservice.event.CourseCreatedEvent

# Ignore Java type information from producer headers.
spring.kafka.consumer.properties[spring.json.use.type.headers]=false

# Allow our local event package for JSON deserialization.
spring.kafka.consumer.properties[spring.json.trusted.packages]=com.rubenmarin.enrollmentservice.event

# Useful while learning: a brand-new consumer group starts with old records.
spring.kafka.consumer.auto-offset-reset=earliest

# Keycloak realm trusted to issue access tokens.
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8083/realms/climbing

# This API must be an intended recipient of the access token.
spring.security.oauth2.resourceserver.jwt.audiences=enrollment-service

# Expose the diagnostic metrics endpoint.
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.probes.enabled=true
# Enable the HTTP histogram
# Spring Boot supports per-meter histogram configuration with:
# management.metrics.distribution.percentiles-histogram.<meter-name>
# and http.server.requests is our Micrometer meter.
management.metrics.distribution.percentiles-histogram.http.server.requests=true


# Spring Boot default sampling probability is 10%
# 1.0  ? 100% | 0.5  ? ~50% | 0.1  ? ~10%
# For local learning, we want everything
management.tracing.sampling.probability=1.0

management.opentelemetry.tracing.export.otlp.endpoint=http://localhost:4318/v1/traces
management.opentelemetry.tracing.export.otlp.transport=http

#Prometheus ? metrics
#Tempo      ? traces
management.otlp.metrics.export.enabled=false

# Enrollment Service = Kafka consumer
#Tempo + Asynchronous kafka
spring.kafka.listener.observation-enabled=true