spring.application.name=enrollment-service

server.port=8081

management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true

#### MONGODB UUID
spring.mongodb.representation.uuid=standard

#### KAFKA CONSUMER
spring.kafka.consumer.group-id=enrollment-service

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer


# Wrap the real JSON deserializer so deserialization failures
# can be handled by Spring Kafka's container error handling.
# PREVIOUS: spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JacksonJsonDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
##       ?
# Real delegate used by ErrorHandlingDeserializer.
spring.kafka.consumer.properties[spring.deserializer.value.delegate.class]=org.springframework.kafka.support.serializer.JacksonJsonDeserializer


# Deserialize Kafka JSON into Enrollment's own local event class.
spring.kafka.consumer.properties[spring.json.value.default.type]=com.rubenmarin.enrollmentservice.event.CourseCreatedEvent

# Ignore Java type information from producer headers.
spring.kafka.consumer.properties[spring.json.use.type.headers]=false

# Allow our local event package for JSON deserialization.
spring.kafka.consumer.properties[spring.json.trusted.packages]=com.rubenmarin.enrollmentservice.event

# Useful while learning: a brand-new consumer group starts with old records.
spring.kafka.consumer.auto-offset-reset=earliest